-- Coordonnées des salons : ce qu'il faut pour « les salons les plus proches de moi ».
--
-- Les colonnes latitude/longitude existaient depuis V1 mais aucune n'était
-- remplie et personne ne les lisait. Trier par distance demandait donc
-- d'abord de donner un point à chaque salon.
--
-- Le point vient de trois sources, par ordre de confiance décroissant :
--   1. les coordonnées saisies pour ce salon (relevées sur une carte) ;
--   2. le centre de son quartier ;
--   3. le centre de sa ville.
--
-- Un centre de quartier situe à quelques centaines de mètres, un centre de
-- ville à quelques kilomètres. C'est grossier pour afficher « à 800 m », mais
-- suffisant pour l'usage réel : classer les salons d'une ville du plus proche
-- au plus lointain. La précision annoncée dans l'interface suit la source.

------------------------------------------------------------------------------
-- Comparaison de libellés sans accent ni casse
------------------------------------------------------------------------------
-- « Guéliz », « Gueliz » et « GUÉLIZ » désignent le même quartier. L'extension
-- unaccent conviendrait mieux mais n'est pas garantie sur les hébergements
-- gérés ; translate() sur les accents du français et de la transcription
-- arabe couvre ce dont on a besoin, et reste IMMUTABLE — donc indexable.
CREATE OR REPLACE FUNCTION normaliser_libelle(valeur text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
    -- lower() d'abord : il ramène déjà « GUÉLIZ » à « guéliz », le translate
    -- n'a donc que les minuscules accentuées à traiter. Apostrophes et tirets
    -- deviennent des espaces, puis les espaces répétés se réduisent à un seul,
    -- pour que « Centre-ville », « Centre ville » et « centre - ville » se
    -- rejoignent.
    SELECT btrim(regexp_replace(
        translate(
            lower(valeur),
            'àáâäãåéèêëíìîïóòôöõúùûüýÿñç''’-',
            'aaaaaaeeeeiiiiooooouuuuyync   '
        ),
        '\s+', ' ', 'g'
    ))
$$;

COMMENT ON FUNCTION normaliser_libelle(text) IS
    'Minuscules, sans accent, apostrophes et tirets ramenés à l''espace. '
    'Sert à rapprocher un quartier saisi à la main d''un repère connu.';

------------------------------------------------------------------------------
-- Repères géographiques
------------------------------------------------------------------------------
CREATE TABLE repere_geo (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ville      varchar(80) NOT NULL,
    -- NULL = le repère vaut pour la ville entière.
    quartier   varchar(80),
    latitude   double precision NOT NULL,
    longitude  double precision NOT NULL,
    CONSTRAINT chk_repere_latitude  CHECK (latitude  BETWEEN -90  AND 90),
    CONSTRAINT chk_repere_longitude CHECK (longitude BETWEEN -180 AND 180)
);

COMMENT ON TABLE repere_geo IS
    'Centres de villes et de quartiers marocains. Sert à situer un salon dont '
    'les coordonnées exactes n''ont pas été relevées. Table de référence : on '
    'y ajoute des lignes au fil des villes ouvertes, sans toucher au code.';

-- Un seul repère par couple ville/quartier, quelle que soit l'orthographe.
-- coalesce(...,'') parce qu'un index unique laisserait passer plusieurs NULL,
-- soit plusieurs centres pour la même ville.
CREATE UNIQUE INDEX uq_repere_geo_lieu
    ON repere_geo (normaliser_libelle(ville), normaliser_libelle(coalesce(quartier, '')));

INSERT INTO repere_geo (ville, quartier, latitude, longitude) VALUES
    -- Villes
    ('Casablanca',  NULL, 33.5731,  -7.5898),
    ('Rabat',       NULL, 34.0209,  -6.8416),
    ('Marrakech',   NULL, 31.6295,  -7.9811),
    ('Tanger',      NULL, 35.7595,  -5.8340),
    ('Fès',         NULL, 34.0181,  -5.0078),
    ('Agadir',      NULL, 30.4278,  -9.5981),
    ('Meknès',      NULL, 33.8935,  -5.5473),
    ('Oujda',       NULL, 34.6814,  -1.9086),
    ('Tétouan',     NULL, 35.5785,  -5.3684),
    ('Kénitra',     NULL, 34.2610,  -6.5802),
    ('Salé',        NULL, 34.0531,  -6.7985),
    ('Témara',      NULL, 33.9287,  -6.9067),
    ('Mohammedia',  NULL, 33.6861,  -7.3828),
    ('El Jadida',   NULL, 33.2316,  -8.5007),
    ('Essaouira',   NULL, 31.5085,  -9.7595),
    ('Nador',       NULL, 35.1681,  -2.9335),
    ('Safi',        NULL, 32.2994,  -9.2372),
    ('Béni Mellal', NULL, 32.3373,  -6.3498),
    ('Khouribga',   NULL, 32.8811,  -6.9063),
    ('Settat',      NULL, 33.0010,  -7.6165),
    ('Berrechid',   NULL, 33.2655,  -7.5877),
    ('Ouarzazate',  NULL, 30.9335,  -6.9370),
    ('Chefchaouen', NULL, 35.1688,  -5.2636),
    ('Ifrane',      NULL, 33.5333,  -5.1000),
    ('Laâyoune',    NULL, 27.1253, -13.1625),
    ('Dakhla',      NULL, 23.6848, -15.9580),

    -- Quartiers de Casablanca
    ('Casablanca', 'Maarif',        33.5834, -7.6329),
    ('Casablanca', 'Gauthier',      33.5883, -7.6222),
    ('Casablanca', 'Anfa',          33.5892, -7.6528),
    ('Casablanca', 'Racine',        33.5876, -7.6357),
    ('Casablanca', 'Bourgogne',     33.5960, -7.6379),
    ('Casablanca', 'Aïn Diab',      33.5928, -7.6857),
    ('Casablanca', 'Sidi Maarouf',  33.5203, -7.6503),
    ('Casablanca', 'Californie',    33.5340, -7.6350),
    ('Casablanca', 'Oasis',         33.5544, -7.6383),
    ('Casablanca', 'Centre-ville',  33.5945, -7.6167),
    ('Casablanca', 'Habous',        33.5786, -7.6003),
    ('Casablanca', 'Sidi Belyout',  33.5960, -7.6100),

    -- Quartiers de Rabat et Salé
    ('Rabat', 'Agdal',        33.9954, -6.8570),
    ('Rabat', 'Hay Riad',     33.9556, -6.8683),
    ('Rabat', 'Souissi',      33.9723, -6.8358),
    ('Rabat', 'Hassan',       34.0181, -6.8341),
    ('Rabat', 'Océan',        34.0203, -6.8500),
    ('Rabat', 'Médina',       34.0270, -6.8340),
    ('Salé',  'Bettana',      34.0400, -6.8000),

    -- Quartiers de Marrakech
    ('Marrakech', 'Guéliz',      31.6383, -8.0110),
    ('Marrakech', 'Hivernage',   31.6244, -8.0110),
    ('Marrakech', 'Médina',      31.6295, -7.9891),
    ('Marrakech', 'Semlalia',    31.6470, -8.0230),
    ('Marrakech', 'Targa',       31.6480, -8.0470),
    ('Marrakech', 'Palmeraie',   31.6690, -7.9530),
    ('Marrakech', 'Agdal',       31.6050, -7.9840),

    -- Quartiers de Tanger
    ('Tanger', 'Iberia',        35.7700, -5.8100),
    ('Tanger', 'Malabata',      35.7900, -5.7800),
    ('Tanger', 'Marshan',       35.7900, -5.8200),
    ('Tanger', 'Centre-ville',  35.7800, -5.8100),

    -- Autres
    ('Fès',     'Ville nouvelle', 34.0350, -4.9980),
    ('Fès',     'Médina',         34.0650, -4.9770),
    ('Agadir',  'Talborjt',       30.4230, -9.5960),
    ('Agadir',  'Founty',         30.4030, -9.6100),
    ('Meknès',  'Hamria',         33.8930, -5.5540),
    ('Tétouan', 'Centre-ville',   35.5760, -5.3700);

------------------------------------------------------------------------------
-- Cohérence des coordonnées d'un salon
------------------------------------------------------------------------------
-- Une latitude sans longitude ne situe rien : la moitié d'un point est une
-- donnée fausse qui se propage silencieusement dans un calcul de distance.
ALTER TABLE salon
    ADD CONSTRAINT chk_salon_latitude  CHECK (latitude  IS NULL OR latitude  BETWEEN -90  AND 90),
    ADD CONSTRAINT chk_salon_longitude CHECK (longitude IS NULL OR longitude BETWEEN -180 AND 180),
    ADD CONSTRAINT chk_salon_point_complet CHECK ((latitude IS NULL) = (longitude IS NULL));

------------------------------------------------------------------------------
-- Rattrapage des salons déjà enregistrés
------------------------------------------------------------------------------
-- Le quartier d'abord, la ville ensuite : un salon du Maarif est placé au
-- Maarif, pas au centre de Casablanca. WHERE latitude IS NULL : ce rattrapage
-- ne remplace jamais une coordonnée relevée à la main.
UPDATE salon s
   SET latitude = r.latitude, longitude = r.longitude
  FROM repere_geo r
 WHERE s.latitude IS NULL
   AND r.quartier IS NOT NULL
   AND normaliser_libelle(s.ville)    = normaliser_libelle(r.ville)
   AND normaliser_libelle(s.quartier) = normaliser_libelle(r.quartier);

UPDATE salon s
   SET latitude = r.latitude, longitude = r.longitude
  FROM repere_geo r
 WHERE s.latitude IS NULL
   AND r.quartier IS NULL
   AND normaliser_libelle(s.ville) = normaliser_libelle(r.ville);

------------------------------------------------------------------------------
-- Index
------------------------------------------------------------------------------
-- La recherche par distance commence par un cadre latitude/longitude, que cet
-- index sert directement ; le calcul exact ne s'applique qu'aux lignes
-- retenues. Partiel : un salon sans coordonnées n'a rien à y faire.
CREATE INDEX idx_salon_coordonnees
    ON salon (latitude, longitude)
    WHERE latitude IS NOT NULL;
