-- Photos d'un salon.
--
-- Une identité visuelle générée depuis le nom tenait la place jusqu'ici :
-- dégradé, trame de zellige et pictogramme du métier, dessinés, sans rien à
-- charger. C'est bien mieux qu'un cadre vide, et cela reste le repli — un
-- salon qu'on vient d'installer n'a pas encore de photo, et sa carte ne doit
-- pas avoir l'air d'un site en travaux. Mais une photo vend ce qu'un dégradé
-- ne vendra jamais.
--
-- Le fichier n'est pas en base. La table décrit la photo, le binaire vit sur
-- le disque : PostgreSQL n'est pas un serveur de fichiers, et une image en
-- bytea alourdit chaque sauvegarde, chaque réplication et chaque requête qui
-- oublie de l'exclure.
--
-- ⚠️ Conséquence à connaître avant de déployer : le répertoire des photos doit
-- être persistant. Sur un hébergement dont le disque est éphémère — la plupart
-- des offres gérées —, les photos disparaîtraient à chaque redéploiement, sans
-- erreur, avec seulement des images cassées. Il faudra alors un stockage objet.

CREATE TABLE photo_salon (
    id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id   bigint NOT NULL REFERENCES salon(id) ON DELETE CASCADE,

    -- Nom du fichier sur le disque, engendré par le serveur : jamais celui
    -- fourni par l'appelant. Un nom d'origine peut contenir des séparateurs de
    -- chemin, des caractères réservés, ou simplement le nom d'un fichier déjà
    -- présent — trois façons d'écrire ailleurs que prévu.
    fichier    varchar(80) NOT NULL UNIQUE,

    type_mime  varchar(40) NOT NULL,
    taille     integer NOT NULL,

    -- Rang d'affichage. La première photo sert de couverture partout : liste
    -- de résultats, fiche, tunnel.
    ordre      integer NOT NULL DEFAULT 0,

    cree_le    timestamptz NOT NULL DEFAULT now(),

    CONSTRAINT chk_photo_type CHECK (type_mime IN ('image/jpeg', 'image/png', 'image/webp')),
    CONSTRAINT chk_photo_taille CHECK (taille > 0 AND taille <= 5 * 1024 * 1024)
);

-- L'accès se fait toujours par salon, dans l'ordre d'affichage.
CREATE INDEX idx_photo_salon ON photo_salon (salon_id, ordre, id);
