-- Fiche client : ce que le salon sait de ceux qui viennent.
--
-- Rien n'est dénormalisé. La fiche se calcule depuis les réservations, à la
-- demande : une table de clients tenue à jour en parallèle dérive au premier
-- oubli, et un compteur de visites faux est pire qu'absent — on s'appuie
-- dessus pour reconnaître un habitué.
--
-- Seule la note du salon est stockée, parce qu'elle ne se déduit de rien.

------------------------------------------------------------------------------
-- Qu'est-ce que « le même client » ?
------------------------------------------------------------------------------
-- Le téléphone, et non le compte.
--
-- Un salon connaît ses clients par leur numéro : c'est ainsi que le carnet
-- papier fonctionne, et c'est la seule donnée commune aux deux origines de
-- réservation. En ligne, le client a un compte ; au téléphone, le salon saisit
-- un nom et un numéro, sans compte. Se fier au compte couperait en deux la
-- même personne selon la façon dont elle a réservé — celle qui appelle un jour
-- et réserve en ligne le lendemain compterait pour deux, et son historique
-- serait faux des deux côtés.
--
-- Deux limites assumées. Une famille qui partage un numéro apparaît comme une
-- seule personne : c'est aussi ce que voit le salon quand il décroche. Et un
-- compte sans numéro n'a pas de clé téléphonique — on retombe alors sur son
-- identifiant, ce qui le sépare de ses éventuelles réservations par téléphone.
CREATE OR REPLACE FUNCTION normaliser_telephone(valeur text)
RETURNS text
LANGUAGE sql
IMMUTABLE
STRICT
PARALLEL SAFE
AS $$
    SELECT CASE
        -- +212 6 12 34 56 78, 00212…, ou 212… : on garde les neuf chiffres utiles.
        WHEN length(chiffres) = 12 AND chiffres LIKE '212%' THEN '0' || right(chiffres, 9)
        WHEN length(chiffres) = 14 AND chiffres LIKE '00212%' THEN '0' || right(chiffres, 9)
        WHEN length(chiffres) = 10 AND chiffres LIKE '0%'   THEN chiffres
        WHEN length(chiffres) = 9                            THEN '0' || chiffres
        -- Tout le reste est illisible : mieux vaut aucune clé qu'une fausse,
        -- qui rapprocherait deux personnes sans rapport.
        ELSE NULL
    END
    FROM (SELECT regexp_replace(valeur, '[^0-9]', '', 'g') AS chiffres) t
$$;

COMMENT ON FUNCTION normaliser_telephone(text) IS
    'Numéro marocain ramené à sa forme nationale 0XXXXXXXXX. NULL si illisible.';

------------------------------------------------------------------------------
-- La note du salon sur un client
------------------------------------------------------------------------------
CREATE TABLE note_client (
    id        bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id  bigint NOT NULL REFERENCES salon(id) ON DELETE CASCADE,

    -- Clé du client telle que la calcule la fiche : « 0661234567 », ou
    -- « compte:42 » pour un compte sans numéro.
    cle       varchar(40) NOT NULL,

    texte     text NOT NULL,
    maj_le    timestamptz NOT NULL DEFAULT now(),
    maj_par   bigint REFERENCES users(id) ON DELETE SET NULL,

    CONSTRAINT uq_note_client UNIQUE (salon_id, cle)
);

-- La note appartient au salon qui l'écrit, et à lui seul.
--
-- « Toujours en retard », « préfère Sofia », « allergique à l'ammoniaque » :
-- ces phrases sont écrites pour un carnet, pas pour une plateforme. Les
-- partager entre salons ferait suivre un client d'un établissement à l'autre
-- avec une réputation qu'il n'a pas choisie, et que personne ne lui a montrée.
-- La contrainte d'unicité porte donc sur le couple, et toute lecture filtre
-- sur le salon.
COMMENT ON TABLE note_client IS
    'Note privée d''un salon sur un de ses clients. Jamais partagée entre salons.';

CREATE INDEX idx_note_client_salon ON note_client (salon_id);

------------------------------------------------------------------------------
-- Ce que la fiche interroge
------------------------------------------------------------------------------
-- L'agrégation groupe les réservations d'un salon par clé de client. Sans cet
-- index, elle balaie toute la table à chaque ouverture de l'écran.
CREATE INDEX idx_reservation_salon_client
    ON reservation (salon_id, client_id, client_telephone_libre);
