-- Socle : utilisateurs, salons, prestations.
-- Reprend l'état issu du jalon J0, enrichi des champs nécessaires à la
-- recherche (ville, géolocalisation, catégorie) et à la modération (statut).

CREATE TABLE users (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    keycloak_id VARCHAR(64)  NOT NULL UNIQUE,
    username    VARCHAR(100) NOT NULL UNIQUE,
    email       VARCHAR(180),
    full_name   VARCHAR(150),
    telephone   VARCHAR(20),
    role        VARCHAR(20)  NOT NULL,
    enabled     BOOLEAN      NOT NULL DEFAULT TRUE,
    cree_le     TIMESTAMPTZ  NOT NULL DEFAULT now()
);

CREATE TABLE salon (
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id                BIGINT REFERENCES users (id) ON DELETE SET NULL,
    nom                     VARCHAR(120) NOT NULL,
    description             TEXT,
    adresse                 VARCHAR(200),
    ville                   VARCHAR(80),
    quartier                VARCHAR(80),
    latitude                DOUBLE PRECISION,
    longitude               DOUBLE PRECISION,
    telephone               VARCHAR(20),
    email                   VARCHAR(180),
    categorie               VARCHAR(20)  NOT NULL DEFAULT 'COIFFURE',
    -- Un salon n'est visible publiquement qu'une fois validé par la plateforme.
    statut                  VARCHAR(20)  NOT NULL DEFAULT 'EN_ATTENTE',
    delai_annulation_heures INT          NOT NULL DEFAULT 24,
    cree_le                 TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_salon_statut    CHECK (statut IN ('EN_ATTENTE', 'ACTIF', 'SUSPENDU')),
    CONSTRAINT chk_salon_categorie CHECK (categorie IN ('COIFFURE', 'BARBIER', 'ONGLERIE', 'ESTHETIQUE', 'SPA'))
);

-- La recherche filtre sur ville en insensible à la casse : l'index doit porter
-- sur la même expression, sinon il n'est pas utilisé.
CREATE INDEX idx_salon_ville  ON salon (LOWER(ville));
CREATE INDEX idx_salon_statut ON salon (statut);

CREATE TABLE prestation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id      BIGINT       NOT NULL REFERENCES salon (id) ON DELETE CASCADE,
    nom           VARCHAR(120) NOT NULL,
    description   VARCHAR(500),
    categorie     VARCHAR(60),
    prix          NUMERIC(10, 2) NOT NULL,
    duree_minutes INT          NOT NULL,
    actif         BOOLEAN      NOT NULL DEFAULT TRUE,
    ordre         INT          NOT NULL DEFAULT 0,
    CONSTRAINT chk_prestation_prix  CHECK (prix > 0),
    CONSTRAINT chk_prestation_duree CHECK (duree_minutes BETWEEN 5 AND 480)
);

CREATE INDEX idx_prestation_salon ON prestation (salon_id);
