-- Praticiens et règles de disponibilité.
--
-- Sans entité employé, un salon à trois fauteuils ne pourrait accepter qu'un
-- client à la fois, et l'étape « avec qui ? » du tunnel de réservation —
-- centrale dans ce métier — n'existerait pas.

CREATE TABLE employe (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id  BIGINT      NOT NULL REFERENCES salon (id) ON DELETE CASCADE,
    -- Nul tant que la personne n'a pas de compte : on peut inscrire une
    -- coiffeuse à l'agenda avant qu'elle ne se connecte.
    user_id   BIGINT      REFERENCES users (id) ON DELETE SET NULL,
    prenom    VARCHAR(80) NOT NULL,
    nom       VARCHAR(80),
    titre     VARCHAR(80),
    photo_url VARCHAR(500),
    -- Désactivation plutôt que suppression : on conserve l'historique des
    -- réservations d'un praticien parti.
    actif     BOOLEAN     NOT NULL DEFAULT TRUE,
    ordre     INT         NOT NULL DEFAULT 0
);

CREATE INDEX idx_employe_salon ON employe (salon_id);

-- Qui sait faire quoi.
CREATE TABLE employe_prestation (
    employe_id               BIGINT NOT NULL REFERENCES employe (id) ON DELETE CASCADE,
    prestation_id            BIGINT NOT NULL REFERENCES prestation (id) ON DELETE CASCADE,
    -- Le senior fait la couleur en 40 min, l'apprenti en 60.
    duree_specifique_minutes INT,
    PRIMARY KEY (employe_id, prestation_id),
    CONSTRAINT chk_ep_duree CHECK (duree_specifique_minutes IS NULL
                                   OR duree_specifique_minutes BETWEEN 5 AND 480)
);

-- Récurrence hebdomadaire. Deux lignes pour une journée coupée par la pause
-- déjeuner (09:00-12:00 puis 14:00-19:00).
-- La cible est soit le salon, soit un employé, jamais les deux : un employé
-- sans horaire propre hérite de celui du salon.
CREATE TABLE horaire_ouverture (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id     BIGINT   REFERENCES salon (id) ON DELETE CASCADE,
    employe_id   BIGINT   REFERENCES employe (id) ON DELETE CASCADE,
    -- Numérotation ISO-8601 : lundi = 1, dimanche = 7.
    jour_semaine SMALLINT NOT NULL,
    heure_debut  TIME     NOT NULL,
    heure_fin    TIME     NOT NULL,
    CONSTRAINT chk_horaire_cible      CHECK ((salon_id IS NULL) <> (employe_id IS NULL)),
    CONSTRAINT chk_horaire_jour       CHECK (jour_semaine BETWEEN 1 AND 7),
    CONSTRAINT chk_horaire_intervalle CHECK (heure_fin > heure_debut)
);

CREATE INDEX idx_horaire_salon   ON horaire_ouverture (salon_id, jour_semaine);
CREATE INDEX idx_horaire_employe ON horaire_ouverture (employe_id, jour_semaine);

-- Exception ponctuelle : congé, formation, fermeture exceptionnelle.
CREATE TABLE absence (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salon_id   BIGINT      REFERENCES salon (id) ON DELETE CASCADE,
    employe_id BIGINT      REFERENCES employe (id) ON DELETE CASCADE,
    debut      TIMESTAMPTZ NOT NULL,
    fin        TIMESTAMPTZ NOT NULL,
    motif      VARCHAR(200),
    CONSTRAINT chk_absence_cible      CHECK ((salon_id IS NULL) <> (employe_id IS NULL)),
    CONSTRAINT chk_absence_intervalle CHECK (fin > debut)
);

CREATE INDEX idx_absence_salon   ON absence (salon_id, debut);
CREATE INDEX idx_absence_employe ON absence (employe_id, debut);
