-- Refonte de la réservation, et suppression de la table creneau.
--
-- Pourquoi creneau disparaît :
--
--  1. Volume. Un salon ouvert 6 j/7, 10 h/j, au pas de 15 min, avec 3 praticiens,
--     représente environ 2 900 lignes par semaine — à pré-générer, maintenir et
--     purger, pour chaque salon.
--  2. Impossibilité structurelle. Le lien était OneToOne entre creneau et
--     reservation : une prestation de 45 min doit occuper trois créneaux
--     consécutifs, ce que ce lien interdit.
--  3. Rigidité. Changer un horaire d'ouverture aurait imposé de régénérer des
--     milliers de lignes.
--
-- À la place, on stocke les règles (horaires, absences) et les réservations
-- confirmées ; les créneaux libres sont calculés à la demande.

DROP TABLE IF EXISTS creneau CASCADE;

CREATE TABLE reservation (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id     BIGINT      NOT NULL REFERENCES users (id),
    salon_id      BIGINT      NOT NULL REFERENCES salon (id),
    employe_id    BIGINT      REFERENCES employe (id) ON DELETE SET NULL,
    -- ON DELETE SET NULL et non CASCADE : supprimer une prestation du catalogue
    -- ne doit pas effacer l'historique des rendez-vous déjà honorés.
    prestation_id BIGINT      REFERENCES prestation (id) ON DELETE SET NULL,

    debut         TIMESTAMPTZ NOT NULL,
    fin           TIMESTAMPTZ NOT NULL,

    statut        VARCHAR(20) NOT NULL DEFAULT 'CONFIRMEE',

    -- Prix et libellé figés à la réservation : si le salon augmente son tarif
    -- demain, le rendez-vous déjà pris ne doit pas changer de prix.
    prix_fige           NUMERIC(10, 2) NOT NULL,
    nom_prestation_fige VARCHAR(120)   NOT NULL,

    note_client   VARCHAR(500),
    cree_le       TIMESTAMPTZ NOT NULL DEFAULT now(),
    annulee_le    TIMESTAMPTZ,

    CONSTRAINT chk_reservation_intervalle CHECK (fin > debut),
    -- ANNULEE_CLIENT et ANNULEE_SALON sont distincts : ils ne pèsent pas de la
    -- même façon dans les statistiques ni dans la fiabilité d'un client.
    CONSTRAINT chk_reservation_statut CHECK (statut IN (
        'EN_ATTENTE', 'CONFIRMEE', 'ANNULEE_CLIENT', 'ANNULEE_SALON', 'HONOREE', 'ABSENT'
    ))
);

CREATE INDEX idx_reservation_client  ON reservation (client_id, debut DESC);
CREATE INDEX idx_reservation_salon   ON reservation (salon_id, debut);
-- Index principal du moteur de disponibilité : « que fait ce praticien ce jour-là ? »
CREATE INDEX idx_reservation_employe ON reservation (employe_id, debut);
