-- Journal des notifications.
--
-- Sert deux objectifs :
--
--  1. Idempotence. La contrainte d'unicité (reservation, type, canal) empêche
--     d'envoyer deux fois le même message — un planificateur qui repasse, un
--     redéploiement au mauvais moment, et le client reçoit son rappel en
--     double. On insère AVANT d'envoyer : si l'insertion échoue, un autre
--     s'en charge déjà.
--  2. Traçabilité. « Le client dit n'avoir rien reçu » se tranche en une
--     requête plutôt qu'en fouillant des logs.

CREATE TABLE notification (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT       NOT NULL REFERENCES reservation (id) ON DELETE CASCADE,
    type           VARCHAR(30)  NOT NULL,
    canal          VARCHAR(20)  NOT NULL,
    destinataire   VARCHAR(180) NOT NULL,
    creee_le       TIMESTAMPTZ  NOT NULL DEFAULT now(),
    envoyee_le     TIMESTAMPTZ,
    erreur         TEXT,

    CONSTRAINT uk_notification_unique UNIQUE (reservation_id, type, canal),
    CONSTRAINT chk_notification_type CHECK (type IN (
        'CONFIRMATION_CLIENT', 'CONFIRMATION_SALON', 'RAPPEL_CLIENT', 'ANNULATION_SALON'
    )),
    CONSTRAINT chk_notification_canal CHECK (canal IN ('EMAIL', 'SMS', 'WHATSAPP'))
);

-- Le planificateur cherche « quels rappels restent à envoyer » : il balaie les
-- réservations, pas les notifications. L'index sert la jointure inverse.
CREATE INDEX idx_notification_reservation ON notification (reservation_id, type);
