-- Avis clients.
--
-- La contrainte décisive est l'unicité sur reservation_id : un avis est
-- rattaché à un rendez-vous réellement honoré, et un rendez-vous ne peut en
-- porter qu'un seul. C'est ce lien — et non un captcha ou une modération a
-- priori — qui rend les faux avis structurellement impossibles : il faudrait
-- avoir pris, payé et honoré un rendez-vous pour en déposer un.

CREATE TABLE avis (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reservation_id BIGINT      NOT NULL UNIQUE REFERENCES reservation (id) ON DELETE CASCADE,
    salon_id       BIGINT      NOT NULL REFERENCES salon (id) ON DELETE CASCADE,
    employe_id     BIGINT      REFERENCES employe (id) ON DELETE SET NULL,
    client_id      BIGINT      REFERENCES users (id) ON DELETE SET NULL,

    note           SMALLINT    NOT NULL,
    commentaire    VARCHAR(1000),

    -- Droit de réponse du salon : un avis négatif auquel le gérant répond
    -- posément fait souvent meilleure impression qu'un avis neutre.
    reponse_salon  VARCHAR(1000),
    reponse_le     TIMESTAMPTZ,

    statut         VARCHAR(20) NOT NULL DEFAULT 'PUBLIE',
    cree_le        TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT chk_avis_note   CHECK (note BETWEEN 1 AND 5),
    CONSTRAINT chk_avis_statut CHECK (statut IN ('PUBLIE', 'MASQUE'))
);

-- Requête dominante : les avis publiés d'un salon, du plus récent au plus ancien.
CREATE INDEX idx_avis_salon ON avis (salon_id, statut, cree_le DESC);

-- Note dénormalisée sur le salon.
--
-- Recalculée à chaque écriture d'avis plutôt que jointe à la volée : la liste
-- de résultats affiche la note de chaque salon, et une sous-requête d'agrégat
-- par ligne se paierait cher dès quelques centaines de salons.
ALTER TABLE salon
    ADD COLUMN note_moyenne NUMERIC(2, 1),
    ADD COLUMN nombre_avis  INT NOT NULL DEFAULT 0;
