-- Demandes de démonstration : le point d'entrée des professionnels.
--
-- Un salon ne s'inscrit pas — l'équipe l'installe. Reste à savoir qui
-- démarcher : cette table est la file d'attente commerciale, remplie par un
-- formulaire public qui ne crée aucun compte.
--
-- Les champs de qualification ne sont pas décoratifs. Savoir si le gérant est
-- propriétaire de son local, depuis combien de temps il exerce et combien de
-- personnes travaillent avec lui décide de l'ordre des visites : un institut
-- de six praticiennes installé depuis cinq ans ne se traite pas comme un
-- projet d'ouverture.

CREATE TABLE demande_demo (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    -- ---- L'établissement ----
    nom_etablissement   VARCHAR(150) NOT NULL,
    type_etablissement  VARCHAR(30)  NOT NULL,
    -- Texte libre : « extensions de cils », « coiffure afro », « beldi ».
    -- Une liste fermée aurait perdu ce qui distingue l'établissement.
    specialite          VARCHAR(150),
    ville               VARCHAR(100) NOT NULL,
    quartier            VARCHAR(100),

    -- ---- La qualification ----
    anciennete          VARCHAR(20)  NOT NULL,
    nombre_collaborateurs SMALLINT,
    proprietaire_local  BOOLEAN,
    -- Ce qu'il utilise aujourd'hui : carnet papier, autre logiciel, rien.
    -- Le discours n'est pas le même, et la reprise de données non plus.
    outil_actuel        VARCHAR(100),

    -- ---- Le contact ----
    prenom              VARCHAR(80)  NOT NULL,
    nom                 VARCHAR(80),
    telephone           VARCHAR(20)  NOT NULL,
    email               VARCHAR(190) NOT NULL,
    -- Identifiant Commun de l'Entreprise : 15 chiffres, l'équivalent
    -- marocain du SIRET. Facultatif — le demander tôt fait fuir, et il n'est
    -- utile qu'au moment du contrat.
    ice                 VARCHAR(15),

    message             VARCHAR(1000),

    -- ---- Le suivi ----
    statut              VARCHAR(20)  NOT NULL DEFAULT 'NOUVELLE',
    note_interne        VARCHAR(1000),
    -- Renseigné à la conversion : la demande mène au salon référencé, ce qui
    -- permet de mesurer le rendement réel du formulaire.
    salon_id            BIGINT       REFERENCES salon (id) ON DELETE SET NULL,

    cree_le             TIMESTAMPTZ  NOT NULL DEFAULT now(),
    traite_le           TIMESTAMPTZ,
    traite_par          BIGINT       REFERENCES users (id) ON DELETE SET NULL,

    CONSTRAINT chk_demande_statut CHECK (
        statut IN ('NOUVELLE', 'CONTACTEE', 'QUALIFIEE', 'CONVERTIE', 'PERDUE')),
    CONSTRAINT chk_demande_type CHECK (
        type_etablissement IN ('COIFFURE', 'BARBIER', 'ONGLERIE', 'ESTHETIQUE',
                               'SPA_HAMMAM', 'AUTRE')),
    CONSTRAINT chk_demande_anciennete CHECK (
        anciennete IN ('EN_PROJET', 'MOINS_1_AN', 'DE_1_A_3_ANS', 'PLUS_3_ANS')),
    CONSTRAINT chk_demande_collaborateurs CHECK (
        nombre_collaborateurs IS NULL OR nombre_collaborateurs BETWEEN 1 AND 200)
);

-- Requête dominante de l'écran d'administration : les demandes d'un statut,
-- les plus récentes d'abord.
CREATE INDEX idx_demande_statut ON demande_demo (statut, cree_le DESC);

-- Sert au garde anti-doublon : on refuse une seconde demande de la même
-- adresse dans les vingt-quatre heures, sans quoi un formulaire public se
-- remplit tout seul.
CREATE INDEX idx_demande_email ON demande_demo (lower(email), cree_le DESC);
